### ISSUE TITLE
Using Snippet in the Url field of a HTML button not working

### ISSUE THREAD

**Issue by SergioFerraresi** [XRM-OSS/Xrm-Html-Templating#36]
Hi,

after installing version **3.9.5** of the Xrm.Oss.Xrm-Templating-Language solution, we have noticed an issue with the **url** of an **HTML Button.**
Inside the field **Url** we inserted a Snippet, that contains the url to be used.
The issue is that the url linked by the button is not the one contained in the snippet (we made sure that the snippet is properly resolved when used in another place, in a Link for example).

![CaptureSnipping](https://user-images.githubusercontent.com/82865862/216624101-17d5a84f-a43a-4a38-8fc3-accd88d5e9fb.PNG)

**Comment by DigitalFlow** [comment]
Hi @SergioFerraresi,

can you try removing the unique name from the snippet you configured?
That should remove the Snippet function call.

Kind regards,
Florian

**Comment by SergioFerraresi** [comment]
Hi Florian,

Thank you for your feedback.
The wrong URL that we got was so composed:
https://[crm_organizationroot]/%7b638132944600000166%7d/webresources/msdyn_/RichTextEditorControl/Preview/browserPreviewFrame.html#

I replaced the name of the organization of our CRM.

We de-installed version 3.9.5 of the Xrm.Oss.Xrm-Templating-Language solution and installed the previous version of it and this solved the issue.
Please let me know in case you need further details.
Viele Grüsse,

Sergio Ferraresi

**Comment by DigitalFlow** [comment]
Hi @SergioFerraresi,

glad that you found a workaround.

If you want to update to the latest version, I also found out the reason why it was not working.

If you put something like `${{Snippet("abc")}}` as link url, the xtl expression broke, because the unlayer editor escaped the quotes and turned it into `${{Snippet(&quot;abc&quot;)}}`, which is not valid XTL.

By switching to single quotes instead of double quotes, unlayer does not replace anything anymore and the XTL survives.
Should look like this then: `${{Snippet('abc')}}.

Kind regards,
Florian
